#!/bin/bash

test -x cwebp && exit 0
wget -c https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.1.0-linux-x86-64.tar.gz -O - | tar -zxOvf - libwebp-1.1.0-linux-x86-64/bin/cwebp > cwebp
chmod +x cwebp